# Actividades Tema 1

In [1]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

## 1. Implementa en Python las funciones siguientes:

### a) Dados dos vectores u, v ∈ R n, la proyección u sobre v y la ortogonal de u sobre v.


In [2]:
def producto_escalar(v1, v2):
    if len(v1) != len(v2):
        return "error: longitudes de los vectores distintas"
    else:
        n = len(v1)
        suma_prod = 0
        for i in range(n):
            suma_prod += v1[i]*v2[i]
        return suma_prod
    
def proyeccion_u_sobre_v(u, v):
    # Función para retornar la proyección del vector u sobre el vector v
    numerador = producto_escalar(u, v)
    denominador = producto_escalar(v, v)
    
    if denominador == 0:
        return "Error: el vector v es 0"
    else:
        proj_u_v = (numerador/denominador)*v
        return proj_u_v
    
def ortogonal_u_sobre_v(u, v):
    # Función para retornar el vector ortogonal de u sobre v
    return u-proyeccion_u_sobre_v(u, v)

#### * Generar vectores aleatorios de tamaño n

In [3]:
n = 3
vec1 = np.random.rand(n)
vec2 = np.random.rand(n)
proy_u_v = proyeccion_u_sobre_v(vec1, vec2)
ort_u_v = ortogonal_u_sobre_v(vec1, vec2)
print(vec1)
print(vec2)
producto_escalar(proy_u_v, ort_u_v)

[0.93327653 0.19410889 0.16223943]
[0.97290188 0.30640913 0.10462327]


-4.597017211338539e-17

la proyección de u sobre v y la ortogonal de u sobre v son ortogonales

#### * Demostrar que proj de u sobre v, producto escalar con ort u sobre v es 0

![title](prueba_projxort_0.jpeg)

## Código interactivo para graficar la proyección y ortogonal de 2 vectores

In [4]:
def plot_proyeccion_and_ortogonal(x1, y1, x2, y2):
    fig, ax = plt.subplots(1)
    ax.set_xlim((-30, 30))
    ax.set_ylim((-30, 30))
    
    a = np.array([x1, y1])
    b = np.array([x2, y2])
    proy_a_sobre_b = proyeccion_u_sobre_v(a, b)
    ort_a_sobre_b = ortogonal_u_sobre_v(a, b)
    
    # plot vector a=(x1,y1)
    ax.quiver(*[0,0],
           a[0],
           a[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["b"],
          label="a=(x1, y1)")
    
    # plot vector b=(x2, y2)
    ax.quiver(*[0,0],
           b[0],
           b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["g"],
          label="b=(x2,y2)")
    
    
    # plot the projection of a over b
    ax.quiver(*[0,0],
           proy_a_sobre_b[0],
           proy_a_sobre_b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["r"],
          label="projection a over b")
    
    # plot the ortogonal of a over b
    ax.quiver(*[0,0],
           ort_a_sobre_b[0],
           ort_a_sobre_b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["k"],
          label="orthogonal a over b")
    
    plt.legend()
    plt.show()

In [6]:
interactive_plot = interactive(plot_proyeccion_and_ortogonal,
                               x1=widgets.IntSlider(min=-30, max=30, step=1, value=10),
                               y1=widgets.IntSlider(min=-30, max=30, step=1, value=0),
                               x2=widgets.IntSlider(min=-30, max=30, step=1, value=10),
                               y2=widgets.IntSlider(min=-30, max=30, step=1, value=10),)
output = interactive_plot.children[-1]
output.layout.height = '350px'
interactive_plot

interactive(children=(IntSlider(value=10, description='x1', max=30, min=-30), IntSlider(value=0, description='…

Nótese cómo las líneas roja (proyección) y negra (ortogonal) son ortogonales entre ellas siempre

### b) dadas dos matrices de entrada A y B:
* comprobación de que sus dimenciones son compatibles para realizar el producto
* En tal caso retornar C = A*B
* NOTA: no se puede usar ninguna función que implemente directamente el producto de dos matrices

In [7]:
def multiplicar_matrices(A, B):
    # función para multiplicar 2 matrices
    # primero se verifica que las dimensiones sean correctas para proceder a la multiplicación
    
    n_a, m_a = A.shape # filas y columnas de A
    n_b, m_b = B.shape # filas y columnas de B
    C = np.zeros((n_a, m_b)) # matriz de zeros de tamaño n_a x m_b
    if m_a != n_b:
        return "Error: las dimensiones de las matrices no son compatibles para el producto"
    else:
        for fila_A in range(n_a):
            for col_B in range(m_b):
                elem = producto_escalar(A[fila_A, :], B[:, col_B])
                C[fila_A, col_B] = elem
        return C

Se comprobará que la función anteriormente definida está correcta por medio de la comparación del resultado de mi solución vs la solución de un paquete de numpy que ya implementa la multiplicación matricial

In [8]:
## Comprobación de la función
mat1 = np.array([[1, 2],
                [3, 4],
                [1, 0]])

mat2 = np.array([[5,6],
                [7, 8]])

In [9]:
# mi solución
mi_solucion = multiplicar_matrices(mat1, mat2)

# operación para comprobar
python_solucion = np.dot(mat1, mat2)

print("mi solución:")
print(mi_solucion)
print("solución de python (para comprobar):")
print(python_solucion)

print()
print("entradas iguales:")
print(mi_solucion==python_solucion)

mi solución:
[[19. 22.]
 [43. 50.]
 [ 5.  6.]]
solución de python (para comprobar):
[[19 22]
 [43 50]
 [ 5  6]]

entradas iguales:
[[ True  True]
 [ True  True]
 [ True  True]]


En efecto las soluciones son iguales

### c) Dada una matriz A:
* comprobación de que sea una matriz cuadrada
* en tal caso calcular su determinante
* NOTA: la implementación del determinante no debe incluir ninguna función que calcule directamente el determinante de una matriz

In [10]:
# Lo haré por el método de cofactores

In [11]:
def calcular_determinante(mat):
    # esta función retorna el determinante de una matriz cuadrada
#     print(mat)
    n = mat.shape[0] # la matriz es de nxn
    
    if n == 1: # si la matriz es de tamaño 1, retorne el escalar
        return mat[0, 0]
    
    determinante = 0
    for pos_adj in range(mat.shape[1]): # por cada posición de la primera fila
#         print(pos_adj)
        cofactor = mat[0, pos_adj]
        signo = (-1)**pos_adj
#         print(cofactor*signo)
        a = mat[1:, :pos_adj] # la submatriz a la izquierda de la columna pos_adj
        b = mat[1:, pos_adj+1:] # la submatriz a la derecha de la columna pos_adj
        adjunta = np.concatenate((a, b), axis=1) # la matriz adjunta
#         print("shape adjunta", adjunta.shape)
#         print(adjunta)
        determinante += signo*cofactor*calcular_determinante(adjunta)
    return determinante

In [12]:
## Comprobación de que la función funciona
mat1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [1, 2,6, 3],
                 [23, 11, 22, 666]]
)
mat2 = np.array([[1, 2],
                 [3,4]])
mat3 = np.array([[2, 3, 1],
                 [0, -2, 5],
                 [3, 7, -4]])
mat1

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  1,   2,   6,   3],
       [ 23,  11,  22, 666]])

In [13]:
def comparar_matrices(mat):
    print(mat)
    print("determinante python:", np.linalg.det(mat))
    print("determinante mío:",calcular_determinante(mat))
    print()
for mat in [mat1, mat2, mat3, np.random.rand(8,8)]:
    comparar_matrices(mat)

[[  1   2   3   4]
 [  5   6   7   8]
 [  1   2   6   3]
 [ 23  11  22 666]]
determinante python: -8239.999999999998
determinante mío: -8240

[[1 2]
 [3 4]]
determinante python: -2.0000000000000004
determinante mío: -2

[[ 2  3  1]
 [ 0 -2  5]
 [ 3  7 -4]]
determinante python: -2.9999999999999982
determinante mío: -3

[[0.68594781 0.61439065 0.09001847 0.77121999 0.6580399  0.97569631
  0.9979933  0.46472709]
 [0.09870619 0.82921122 0.3050123  0.91203902 0.09085159 0.2352909
  0.5345006  0.76250948]
 [0.44719336 0.59628772 0.19112878 0.03595    0.45871076 0.63649734
  0.41088473 0.80511625]
 [0.17676842 0.83260225 0.26500851 0.01952837 0.83562369 0.51122165
  0.25703007 0.40140238]
 [0.26111822 0.22008712 0.01523801 0.78188309 0.18987359 0.22875986
  0.5808142  0.52486818]
 [0.76148376 0.95888271 0.38709001 0.11792831 0.76831703 0.78893102
  0.33158487 0.75988631]
 [0.88515047 0.46648439 0.13475755 0.54536671 0.31494253 0.7273625
  0.22270003 0.50514813]
 [0.87798299 0.56451443 0.84052

## 2. Realizar diferentos programas en python que dada una matriz A E R nxn y k, calcule A^k

### a) multiplica secuencialmente la matriz A mediante la función anteriormente implementada

In [14]:
def potencia_matriz_secuencial(A, k):
    # esta función retorna A^k, por medio de multiplicar secuencialmente
    # la matriz A
    A_pow_k = A
    for i in range(k-1):
        A_pow_k = multiplicar_matrices(A_pow_k, A)
    return A_pow_k

In [191]:
# probar la anterior
n=4
A = np.random.rand(n,n)

In [240]:
k = 56
resp_mia =potencia_matriz_secuencial(A, k) 
print(resp_mia)
print()
resp_python =np.linalg.matrix_power(A, k) 
print(resp_python)

[[1.42224568e+16 2.23514723e+16 2.01845640e+16 1.38446988e+16]
 [9.63072394e+15 1.51352795e+16 1.36679595e+16 9.37492541e+15]
 [1.13401076e+16 1.78216818e+16 1.60939231e+16 1.10389067e+16]
 [1.01127463e+16 1.58928075e+16 1.43520474e+16 9.84414495e+15]]

[[1.42224568e+16 2.23514723e+16 2.01845640e+16 1.38446988e+16]
 [9.63072394e+15 1.51352795e+16 1.36679595e+16 9.37492541e+15]
 [1.13401076e+16 1.78216818e+16 1.60939231e+16 1.10389067e+16]
 [1.01127463e+16 1.58928075e+16 1.43520474e+16 9.84414495e+15]]


### b) Aprovechando la forma diagonalizada de A

In [15]:
np.linalg.eig(mat)

(array([ 4.0866012 +0.j        ,  0.50326621+0.18255907j,
         0.50326621-0.18255907j, -0.54942999+0.36358386j,
        -0.54942999-0.36358386j,  0.23614445+0.j        ,
        -0.47316385+0.j        , -0.17640919+0.j        ]),
 array([[ 0.45033219+0.j        , -0.26419674-0.24647651j,
         -0.26419674+0.24647651j, -0.12611615-0.00159268j,
         -0.12611615+0.00159268j,  0.08713168+0.j        ,
          0.45652508+0.j        , -0.48453736+0.j        ],
        [ 0.30954368+0.j        ,  0.65915836+0.j        ,
          0.65915836-0.j        , -0.06061249+0.18641126j,
         -0.06061249-0.18641126j,  0.64982956+0.j        ,
          0.27137443+0.j        , -0.26535552+0.j        ],
        [ 0.32075991+0.j        , -0.299692  +0.21406828j,
         -0.299692  -0.21406828j,  0.44485203+0.01260163j,
          0.44485203-0.01260163j, -0.12662452+0.j        ,
         -0.35587382+0.j        ,  0.15056437+0.j        ],
        [ 0.26826913+0.j        ,  0.29859416-0.0210433