# Actividades Tema 1

In [1]:
from __future__ import print_function
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import time

%matplotlib inline

## 1. Implementa en Python las funciones siguientes:

### a) Dados dos vectores u, v ∈ R n, la proyección u sobre v y la ortogonal de u sobre v.


In [2]:
def producto_escalar(v1, v2):
    if len(v1) != len(v2):
        return "error: longitudes de los vectores distintas"
    else:
        n = len(v1)
        suma_prod = 0
        for i in range(n):
            suma_prod += v1[i]*v2[i]
        return suma_prod
    
def proyeccion_u_sobre_v(u, v):
    # Función para retornar la proyección del vector u sobre el vector v
    numerador = producto_escalar(u, v)
    denominador = producto_escalar(v, v)
    
    if denominador == 0:
        return "Error: el vector v es 0"
    else:
        proj_u_v = (numerador/denominador)*v
        return proj_u_v
    
def ortogonal_u_sobre_v(u, v):
    # Función para retornar el vector ortogonal de u sobre v
    return u-proyeccion_u_sobre_v(u, v)

#### * Generar vectores aleatorios de tamaño n

In [3]:
n = 3
vec1 = np.random.rand(n)
vec2 = np.random.rand(n)
proy_u_v = proyeccion_u_sobre_v(vec1, vec2)
ort_u_v = ortogonal_u_sobre_v(vec1, vec2)
print(vec1)
print(vec2)
producto_escalar(proy_u_v, ort_u_v)

[0.01701128 0.91934144 0.64438935]
[0.20822213 0.59180698 0.68217814]


1.6653345369377348e-16

la proyección de u sobre v y la ortogonal de u sobre v son ortogonales

#### * Demostrar que proj de u sobre v, producto escalar con ort u sobre v es 0

![title](prueba_projxort_0.jpeg)

## Código interactivo para graficar la proyección y ortogonal de 2 vectores

In [6]:
def plot_proyeccion_and_ortogonal(x1, y1, x2, y2):
    fig, ax = plt.subplots(1)
    ax.set_xlim((-30, 30))
    ax.set_ylim((-30, 30))
    
    a = np.array([x1, y1])
    b = np.array([x2, y2])
    proy_a_sobre_b = proyeccion_u_sobre_v(a, b)
    ort_a_sobre_b = ortogonal_u_sobre_v(a, b)
    
    # plot vector a=(x1,y1)
    ax.quiver(*[0,0],
           a[0],
           a[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["b"],
          label="a=(x1, y1)")
    
    # plot vector b=(x2, y2)
    ax.quiver(*[0,0],
           b[0],
           b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["g"],
          label="b=(x2,y2)")
    
    
    # plot the projection of a over b
    ax.quiver(*[0,0],
           proy_a_sobre_b[0],
           proy_a_sobre_b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["r"],
          label="projection a over b")
    
    # plot the ortogonal of a over b
    ax.quiver(*[0,0],
           ort_a_sobre_b[0],
           ort_a_sobre_b[1],
           scale=1,
           scale_units='xy',
           angles = 'xy',
           color=["k"],
          label="orthogonal a over b")
    
    plt.legend()
    plt.show()

In [7]:
interactive_plot = interactive(plot_proyeccion_and_ortogonal,
                               x1=widgets.IntSlider(min=-30, max=30, step=1, value=10),
                               y1=widgets.IntSlider(min=-30, max=30, step=1, value=0),
                               x2=widgets.IntSlider(min=-30, max=30, step=1, value=10),
                               y2=widgets.IntSlider(min=-30, max=30, step=1, value=10),)
output = interactive_plot.children[-1]
output.layout.height = '350px'
interactive_plot

interactive(children=(IntSlider(value=10, description='x1', max=30, min=-30), IntSlider(value=0, description='…

Nótese cómo las líneas roja (proyección) y negra (ortogonal) son ortogonales entre ellas siempre

### b) dadas dos matrices de entrada A y B:
* comprobación de que sus dimenciones son compatibles para realizar el producto
* En tal caso retornar C = A*B
* NOTA: no se puede usar ninguna función que implemente directamente el producto de dos matrices

In [7]:
def multiplicar_matrices(A, B):
    # función para multiplicar 2 matrices
    # primero se verifica que las dimensiones sean correctas para proceder a la multiplicación
    
    n_a, m_a = A.shape # filas y columnas de A
    n_b, m_b = B.shape # filas y columnas de B
    C = np.zeros((n_a, m_b)) # matriz de zeros de tamaño n_a x m_b
    if m_a != n_b:
        return "Error: las dimensiones de las matrices no son compatibles para el producto"
    else:
        for fila_A in range(n_a):
            for col_B in range(m_b):
                elem = producto_escalar(A[fila_A, :], B[:, col_B])
                C[fila_A, col_B] = elem
        return C

Se comprobará que la función anteriormente definida está correcta por medio de la comparación del resultado de mi solución vs la solución de un paquete de numpy que ya implementa la multiplicación matricial

In [8]:
## Comprobación de la función
mat1 = np.array([[1, 2],
                [3, 4],
                [1, 0]])

mat2 = np.array([[5,6],
                [7, 8]])

In [9]:
# mi solución
mi_solucion = multiplicar_matrices(mat1, mat2)

# operación para comprobar
python_solucion = np.dot(mat1, mat2)

print("mi solución:")
print(mi_solucion)
print("solución de python (para comprobar):")
print(python_solucion)

print()
print("entradas iguales:")
print(mi_solucion==python_solucion)

mi solución:
[[19. 22.]
 [43. 50.]
 [ 5.  6.]]
solución de python (para comprobar):
[[19 22]
 [43 50]
 [ 5  6]]

entradas iguales:
[[ True  True]
 [ True  True]
 [ True  True]]


En efecto las soluciones son iguales

### c) Dada una matriz A:
* comprobación de que sea una matriz cuadrada
* en tal caso calcular su determinante
* NOTA: la implementación del determinante no debe incluir ninguna función que calcule directamente el determinante de una matriz

In [10]:
# Lo haré por el método de cofactores

In [11]:
def calcular_determinante(mat):
    # esta función retorna el determinante de una matriz cuadrada
#     print(mat)
    n = mat.shape[0] # la matriz es de nxn
    
    if n == 1: # si la matriz es de tamaño 1, retorne el escalar
        return mat[0, 0]
    
    determinante = 0
    for pos_adj in range(mat.shape[1]): # por cada posición de la primera fila
#         print(pos_adj)
        cofactor = mat[0, pos_adj]
        signo = (-1)**pos_adj
#         print(cofactor*signo)
        a = mat[1:, :pos_adj] # la submatriz a la izquierda de la columna pos_adj
        b = mat[1:, pos_adj+1:] # la submatriz a la derecha de la columna pos_adj
        adjunta = np.concatenate((a, b), axis=1) # la matriz adjunta
#         print("shape adjunta", adjunta.shape)
#         print(adjunta)
        determinante += signo*cofactor*calcular_determinante(adjunta)
    return determinante

In [12]:
## Comprobación de que la función funciona
mat1 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [1, 2,6, 3],
                 [23, 11, 22, 666]]
)
mat2 = np.array([[1, 2],
                 [3,4]])
mat3 = np.array([[2, 3, 1],
                 [0, -2, 5],
                 [3, 7, -4]])
mat1

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  1,   2,   6,   3],
       [ 23,  11,  22, 666]])

In [13]:
def comparar_matrices(mat):
    print(mat)
    print("determinante python:", np.linalg.det(mat))
    print("determinante mío:",calcular_determinante(mat))
    print()
for mat in [mat1, mat2, mat3, np.random.rand(8,8)]:
    comparar_matrices(mat)

[[  1   2   3   4]
 [  5   6   7   8]
 [  1   2   6   3]
 [ 23  11  22 666]]
determinante python: -8239.999999999998
determinante mío: -8240

[[1 2]
 [3 4]]
determinante python: -2.0000000000000004
determinante mío: -2

[[ 2  3  1]
 [ 0 -2  5]
 [ 3  7 -4]]
determinante python: -2.9999999999999982
determinante mío: -3

[[0.49755991 0.37436833 0.96244045 0.32602564 0.31636205 0.36546484
  0.74034057 0.54035953]
 [0.41800288 0.47030238 0.95601736 0.19425926 0.8264552  0.26224032
  0.20890685 0.82972881]
 [0.24972857 0.77422682 0.45902499 0.89451438 0.69425429 0.20405023
  0.12479041 0.03536209]
 [0.9322747  0.50962621 0.79206383 0.89435441 0.66507491 0.71569115
  0.00883119 0.67371381]
 [0.62642032 0.70961405 0.78850581 0.64561793 0.4490074  0.29441861
  0.5260514  0.90968455]
 [0.46458584 0.555454   0.78245895 0.43600244 0.43991935 0.06039977
  0.86922355 0.56194545]
 [0.41414081 0.97153973 0.25584209 0.64505457 0.31602025 0.99583776
  0.28983904 0.35270547]
 [0.98501288 0.10422044 0.855

## 2. Realizar diferentos programas en python que dada una matriz A E R nxn y k, calcule A^k

### a) multiplica secuencialmente la matriz A mediante la función anteriormente implementada

In [14]:
def potencia_matriz_secuencial(A, k):
    # esta función retorna A^k, por medio de multiplicar secuencialmente
    # la matriz A
    A_pow_k = A
    for i in range(k-1):
        A_pow_k = multiplicar_matrices(A_pow_k, A)
    return A_pow_k

In [15]:
# probar la anterior
n=4
A = np.random.rand(n,n)

In [16]:
k = 56
resp_mia =potencia_matriz_secuencial(A, k) 
print(resp_mia)
print()
resp_python =np.linalg.matrix_power(A, k) 
print(resp_python)

[[6.04733565e+15 5.67182488e+15 4.76204598e+15 6.50318523e+15]
 [5.41168800e+15 5.07564793e+15 4.26149773e+15 5.81962232e+15]
 [5.12605249e+15 4.80774902e+15 4.03657066e+15 5.51245553e+15]
 [4.77586116e+15 4.47930290e+15 3.76080835e+15 5.13586669e+15]]

[[6.04733565e+15 5.67182488e+15 4.76204598e+15 6.50318523e+15]
 [5.41168800e+15 5.07564793e+15 4.26149773e+15 5.81962232e+15]
 [5.12605249e+15 4.80774902e+15 4.03657066e+15 5.51245553e+15]
 [4.77586116e+15 4.47930290e+15 3.76080835e+15 5.13586669e+15]]


### b) Aprovechando la forma diagonalizada de A

In [195]:
def potencia_matriz_diagonalizar(A, k):
    # esta función retorna A^k, por medio diagonalizar A
    
    w, p = np.linalg.eig(A) # valores y vectores propios respectivamente
    D = np.diag(w**k) # potenciar los valores propios a la k y generar matriz diagonal
    A_pow_k = p.dot(D).dot(np.linalg.inv(p))
    return A_pow_k

In [196]:
# probar la anterior
n = 4
A = np.random.rand(n,n)
k = 56
resp_mia =potencia_matriz_secuencial(A, k) 
print(resp_mia)
print()
resp_python =np.linalg.matrix_power(A, k) 
print(resp_python)

[[ 447112.99564769 1028715.14957649 1016013.90864785  231810.89779178]
 [ 380932.75888581  876448.02063545  865626.77679929  197498.98950645]
 [ 371212.47912484  854083.65380746  843538.53617729  192459.39817247]
 [ 549302.91256493 1263833.15484594 1248228.98162081  284792.44074948]]

[[ 447112.99564768 1028715.14957649 1016013.90864785  231810.89779178]
 [ 380932.75888581  876448.02063545  865626.77679929  197498.98950645]
 [ 371212.47912484  854083.65380746  843538.53617729  192459.39817247]
 [ 549302.91256492 1263833.15484593 1248228.98162081  284792.44074948]]


### c) Comparar los métodos anteriores con matrices simétricas aleatorias

In [187]:
from pseudorandom_matrix import *
tiempos_secuencial = []
tiempos_diagonal = []
num_sim = 20 # número de simulaciones a realizar
n = 50 # tamaño de la matriz nxn
k = 100 # potencia

In [188]:
for i in range(num_sim):
    print("*"*10)
    print(f"simulation number {i}")
    mat = pseudorandom_matrix(n)
    
    print()
    print("starting diagonalized form:")
    start_time = time.time()
    potencia_matriz_diagonalizar(mat, k)
    end_time = time.time() - start_time
    tiempos_diagonal.append(end_time)
    print("elapsed time:",end_time)
    
    print("starting secuential form:")
    start_time = time.time()
    potencia_matriz_secuencial(mat, k)
    end_time = time.time() - start_time
    tiempos_secuencial.append(end_time)
    print("elapsed time:",end_time)
    print("*"*10)
    print()

**********
simulation number 0

starting diagonalized form:
elapsed time: 0.0009968280792236328
starting secuential form:
elapsed time: 5.2212605476379395
**********

**********
simulation number 1

starting diagonalized form:
elapsed time: 0.0009622573852539062
starting secuential form:
elapsed time: 5.275035381317139
**********

**********
simulation number 2

starting diagonalized form:
elapsed time: 0.0009992122650146484
starting secuential form:
elapsed time: 6.11255669593811
**********

**********
simulation number 3

starting diagonalized form:
elapsed time: 0.0009989738464355469
starting secuential form:
elapsed time: 5.608927011489868
**********

**********
simulation number 4

starting diagonalized form:
elapsed time: 0.0
starting secuential form:
elapsed time: 5.796842813491821
**********

**********
simulation number 5

starting diagonalized form:
elapsed time: 0.0009660720825195312
starting secuential form:
elapsed time: 5.533639192581177
**********

**********
simulation 

In [189]:
resultados = pd.DataFrame()
resultados["tiempos_secuencial"] = tiempos_secuencial
resultados["tiempos_diagonal"] = tiempos_diagonal

In [190]:
resultados.describe()

tiempos_secuencial  tiempos_diagonal
count           20.000000         20.000000
mean             5.578749          0.000932
std              0.233497          0.000507
min              5.221261          0.000000
25%              5.469690          0.000951
50%              5.550394          0.000966
75%              5.629206          0.000998
max              6.121665          0.001994

Como se puede observar en la tabla anterior, el tiempo promedio de la potenciación utilizando la diagonalización de una matriz es de solo 0.0009 segundos, mientras que el tiempo promedio de potenciar de manera secuencial es de 5.5 segundos

In [194]:
razon=resultados.tiempos_secuencial.mean()/resultados.tiempos_diagonal.mean()
print(f"¡la forma secuencial es {razon} veces más lenta que la forma diagonal!")

¡la forma secuencial es 5983.549475137767 veces más lenta que la forma diagonal!
